### ISSUE TITLE
A discussion about Markov Decision Processes II

### ISSUE THREAD

**Issue by roy1312** [oyamad/theory14#1]
Oyama sensei, I have 2 questions to discuss about the slide MDP II. 
1. Page 7, on second last line, I think it should be beta^k (it's the same as equation 6.2.11, page 150 in Puterman's chapter, when n = 0). 
2. On page 19,  I am not sure why v^hat is epsilon/2 approximation. I think it should be a result of proposition 6, but I can't see it. 

Thank you very much!

**Comment by oyamad** [comment]
@roy1312 Thanks for pointing out those errors.
1. Yes, you are right; the power must be k, not k+1.
2. v_hat must have been the second term in the second last line in Proposition 6, i.e., it must be
   `Tv + (beta/(1-beta)) * midrange(Tv-v)`,
   where `midrange(z) = (z.min() + z.max()) / 2`.

I have corrected the slides on the course webpage.

**Comment by roy1312** [comment]
Thanks! But if point 1 is true, then the inequality of lemma 2 , and
therefore proposition 4 will be different. It seems to be a mistake in
Puterman's book.

2014-12-23 21:36 GMT+09:00 Daisuke Oyama notifications@github.com:

> @roy1312 https://github.com/roy1312 Thanks for pointing out those
> errors.
> 
>    1.
> 
>    Yes, you are right; the power must be k, not k+1.
>    2.
> 
>    v_hat must have been the second term in the second last line in
>    Proposition 6, i.e., it must be
>    Tv + (beta/(1-beta)) \* midrange(Tv-v),
>    where midrange(z) = (z.min() + z.max()) / 2.
> 
> I have corrected the slides on the course webpage.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/oyamad/theory14/issues/1#issuecomment-67946906.

## 

The University of Tokyo
Master of Economics, Year 2
Shangguan Ruo

**Comment by oyamad** [comment]
Thanks again.

The main mistake has been in the first line of the Proof on page 7:
the second term in the RHS must be | T^m v - T v |, not | T^m - v |.

I have corrected this as well as the relevant indices and the very last term.

**Comment by roy1312** [comment]
I see. Thanks a lot for answering!
