### ISSUE TITLE
Question about Rust paper

### ISSUE THREAD

**Issue by roy1312** [oyamad/theory14#2]
Dear all,

I am having difficulty deriving equation 3.8 of Rust paper. I think it means
u(gamma, 0, theta1) + beta E V_theta(gamma, 0) = u(gamma, 1, theta1) + beta E V_theta(gamma, 1)

but it seems not working. Could you provide some help? Thanks! 

@kusanominal @S-Nakada

**Comment by ghost** [comment]
@roy1312 
Sorry for my slow response.

Actually, I can't manage to derive equation (3.8) too.
Rust said he found the solution (I mean, eq. (3.7) & (3.8)) in the following paper (Theorem 4.2):
http://www.jstor.org/discover/1912654?sid=21105611703253&uid=60&uid=2134&uid=70&uid=2&uid=2488591763&uid=2488591753&uid=3
However, the proof is omitted also in this paper, so it seems there is no paper written by himself that explains how to derive the equation.

Anyway, it seems the derivation cannot be done easily.
I'm wondering if we have to pursue it in detail...

**Comment by oyamad** [comment]
@roy1312 See the derivation in Example 3 in Rust 1996, Section 2.3 in Handbook of Computational Economics.
