### ISSUE TITLE
Question about coding of contraction iteration

### ISSUE THREAD

**Issue by ghost** [oyamad/theory14#3]
I'm having difficulty coding of contraction iteration.

I tried to compute expected value function for the estimated parameters in TABLE X in the paper.
However, it seems that my contraction iteration doesn't work because the expected value takes
the same value among all states.
Furthermore, they are the same value between two different example (B, B2).

Is there something wrong with my code?

Here's ipython notebook:
http://nbviewer.ipython.org/github/kusanominal/Theory14/blob/master/Rust.ipynb

**Comment by oyamad** [comment]
It seems some kind of _underflow_ is occurring.
For the operator `T`, try using [numpy.logaddexp](http://docs.scipy.org/doc/numpy/reference/generated/numpy.logaddexp.html) or [scipy.misc.logsumexp](http://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.logsumexp.html).

**Comment by ghost** [comment]
It seems to work using numpy.logaddexp.
Thank you so much.
